#!/usr/bin/env python

import sys

from rqt_explain_bt.explain_bt_plugin import ExplainBTPlugin
from rqt_gui.main import Main

plugin = 'rqt_explain_bt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))